name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to your default branch if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0  # Change this to your desired Ruby version

    - name: Install gems
      run: |
        gem install kramdown
        gem install rss

    - name: Build website
      run: make build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Change this to the path of your build directory
